server:
  port: 12000
spring:
  # rabbitmq的配置信息；如下配置的rabbit都是默认值，其实可以完全不配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenjieObject/spring-cloud-wenjie-config.git
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
management: # 暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: "bus-refresh"


